name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Save state variables (if needed)
      - name: Save state variables
        run: |
          # Replace with your actual state variables and values
          echo "state_variable1=value1" >> $GITHUB_STATE
          echo "state_variable2=value2" >> $GITHUB_STATE

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # Set output variables (if needed)
      - name: Set output variables
        run: |
          # Replace with your actual output variables and values
          echo "output_variable1=value1" >> $GITHUB_OUTPUT
          echo "output_variable2=value2" >> $GITHUB_OUTPUT

